# Generated by Django 5.2.3 on 2025-10-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='created_when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
